### ISSUE TITLE
Persistent Broken Item Icon in Quick Use Slot

### ISSUE THREAD

**Issue by AndyGnz** [shr0x/ragemp-rp-gamemode#14]
The Quick Use slot in the inventory interface shows an active state with an broken image icon, even after running /clearinventory or rejoining the server. This issue persists across different sessions and seems to affect only the Quick Use slot.

![1](https://github.com/shr0x/ragemp-rp-gamemode/assets/130935056/ccc939cc-6501-40f0-8464-29aaf2113b37)

**Comment by shr0x** [comment]
Hey, thanks for the report, that kind of looks strange will check it out, although would appreciate if you've found a repro way
